### PR TITLE
Release notes for collecting metrics pod details

### PR DESCRIPTION
**Pull request by sridhargaddam**
Related to: https://github.com/submariner-io/subctl/pull/752
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>

### CODE REVIEW

**Comment by sridhargaddam** [comment]
This PR needs to be backported to release-0.15 and release-0.14 branches too.

**Comment by tpantelis** [comment]
On the recent tech exchange call, we decided that we would push PRs to **submariner-website**  in a separate branch rather than pushing files to the repos.

**Comment by sridhargaddam** [comment]
> On the recent tech exchange call, we decided that we would push PRs to **submariner-website** in a separate branch rather than pushing files to the repos.

I see, I could not attend that meeting. Shall we close this PR and create a new one on the **submariner-website**

**Comment by tpantelis** [comment]
> I see, I could not attend that meeting. Shall we close this PR and create a new one on the **submariner-website**

yeah but it needs to created on the `release-notes_0.16` branch but I'm not sure how to get that bootstrapped.

**Comment by skitt** [comment]
> > I see, I could not attend that meeting. Shall we close this PR and create a new one on the **submariner-website**
> 
> yeah but it needs to created on the `release-notes_0.16` branch but I'm not sure how to get that bootstrapped.

I’ve prepared branches for 0.13 through 0.16:

```
git fetch
git checkout -b release-notes-0.16 origin/devel
git push origin release-notes-0.16
```

etc.

These can now be used as targets for release note PRs, and we’ll merge the release note branches to `devel` when the corresponding release is made.

**Pull request closed without merging**
