### PR TITLE
Drop the dependency on wireguard in e2e

### PR DESCRIPTION
**Pull request by skitt**
The dependency breaks Windows builds.

### CODE REVIEW

**Comment by tpantelis** [comment]
The cross-build job doesn't run on draft PRs.

**Review by vthapar — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]

**Comment by tpantelis** [comment]
Shouldn't we merge this?

**Comment by tpantelis** [comment]
I updated the commit hash.

**Comment by skitt** [comment]
> Shouldn't we merge this?

Current `devel` isn’t affected by this, so there’s no urgency. The dependencies will all be aligned when v0.19.0-m0 is released.

**Comment by tpantelis** [comment]
> > Shouldn't we merge this?
> 
> Current `devel` isn’t affected by this, so there’s no urgency. The dependencies will all be aligned when v0.19.0-m0 is released.

yes but that won't be for a while and someone may push a subctl PR before that.

**Comment by skitt** [comment]
> > > Shouldn't we merge this?
> > 
> > 
> > Current `devel` isn’t affected by this, so there’s no urgency. The dependencies will all be aligned when v0.19.0-m0 is released.
> 
> yes but that won't be for a while and someone may push a subctl PR before that.

Current `devel` isn’t affected by the dependency change.

**Pull request closed without merging**
