### PR TITLE
Remove useless empty list check

### PR DESCRIPTION
**Pull request by jinglina**

### CODE REVIEW

**Comment by jinglina** [comment]
remove useless empty list check

**Review by tpantelis — APPROVED** [review]

**Review by skitt — CHANGES_REQUESTED** [review]
This isn’t a useless empty list check: it checks that, when the list of arguments _isn’t_ empty, the first argument isn’t itself empty. Try

    subctl export service ""

You’d never run a command like that intentionally but it can happen if variable expansion is involved.

**Comment by jinglina** [comment]
> This isn’t a useless empty list check: it checks that, when the list of arguments _isn’t_ empty, the first argument isn’t itself empty. Try
> 
> ```
> subctl export service ""
> ```
> 
> You’d never run a command like that intentionally but it can happen if variable expansion is involved.

This is beyond my testing. Thanks. Then I think `subctl join` also need this check  , right?

**Comment by skitt** [comment]
> This is beyond my testing. Thanks. Then I think `subctl join` also need this check , right?

I’m not sure whether it makes sense to keep the test, I’m checking other tools’ behaviour...

**Review by skitt — APPROVED** [review]
OK, applying this results in the same behaviour as `kubectl`, so it’s fine by me.

**Pull request merged**
