### PR TITLE
Bump lighthouse to fix e2e

### PR DESCRIPTION
**Pull request by vthapar**

### CODE REVIEW

**Comment by skitt** [comment]
Heh, now we have a commit saying “Do Not Merge this” in the history ;-).

**Comment by tpantelis** [comment]
> Heh, now we have a commit saying “Do Not Merge this” in the history ;-).

Crap. Sorry I forgot to update the commit too in my haste.

**Comment by skitt** [comment]
> Crap. Sorry I forgot to update the commit too in my haste.

Wasn’t the commit redundant anyway? The dependency will be bumped by the release process.

**Comment by tpantelis** [comment]
> > Crap. Sorry I forgot to update the commit too in my haste.
> 
> Wasn’t the commit redundant anyway? The dependency will be bumped by the release process.

Yes but the release process runs E2E which uses subctl which happens before the bump.

**Pull request merged**
