### PR TITLE
Use `nettest` image/component names from operator

### PR DESCRIPTION
**Pull request by mkolesnik**
Instead of hard coding the name of the image and the component. Use the ones from the operator.
This will allow downstream forks to override with a different image name if desired.

Depends on https://github.com/submariner-io/submariner-operator/pull/2293

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

### CODE REVIEW

**Comment by nyechiel** [comment]
@mkolesnik should we add this as a blocker for 0.14.0-rc0?

**Comment by mkolesnik** [comment]
> @mkolesnik should we add this as a blocker for 0.14.0-rc0?

No, we can always backport it but it shouldn't block the release

**Comment by nyechiel** [comment]
> > @mkolesnik should we add this as a blocker for 0.14.0-rc0?
> 
> No, we can always backport it but it shouldn't block the release

But if we backport later on, would this require another rc and test day? Or are you saying that this is a clean and safe change?

**Comment by mkolesnik** [comment]
> > > @mkolesnik should we add this as a blocker for 0.14.0-rc0?
> > 
> > 
> > No, we can always backport it but it shouldn't block the release
> 
> But if we backport, this would require another rc and test day? Or are you saying this is a clean and safe change?

We're not planning RC1?

This is safe since metrics proxy was just recently added and AFAICT theres no usage of the actual override, so it should be quite safe to backport.

**Comment by nyechiel** [comment]
> > > > @mkolesnik should we add this as a blocker for 0.14.0-rc0?
> > > 
> > > 
> > > No, we can always backport it but it shouldn't block the release
> > 
> > 
> > But if we backport, this would require another rc and test day? Or are you saying this is a clean and safe change?
> 
> We're not planning RC1?
> 

Not at this point (https://github.com/submariner-io/releases/issues/416), but based on feedback (and bugs reported) with rc0 with might need one.

> This is safe since metrics proxy was just recently added and AFAICT theres no usage of the actual override, so it should be quite safe to backport.

**Review by tpantelis — APPROVED** [review]

**Review by skitt — APPROVED** [review]

**Comment by mkolesnik** [comment]
Backported as https://github.com/submariner-io/subctl/pull/336

**Pull request merged**
